name: Scala Steward

# This workflow will launch at 00:00 every day
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    uses: softwaremill/github-actions-workflows/.github/workflows/scala-steward.yml@main
    secrets:
      repo-github-token: ${{secrets.REPO_GITHUB_TOKEN}}
    with:
      java-opts: '-Xmx3500M'